#pragma once

#ifdef RGBLIGHT_ENABLE
// WS2812B 灯带配置（每手 5 颗，仅灯带，无底灯）
#define WS2812_DI_PIN GP29             // 数据引脚
#define RGBLIGHT_LED_COUNT 10               // 总 LED 数（左手 5 + 右手 5）
#define RGBLED_SPLIT { 5, 5 }          // 分体 LED 分配：左手 5 颗，右手 5 颗
#define RGBLIGHT_LIMIT_VAL 120         // 最大亮度
#define RGBLIGHT_HUE_STEP 8            // 色调步长
#define RGBLIGHT_SAT_STEP 8            // 饱和度步长
#define RGBLIGHT_VAL_STEP 8            // 亮度步长

// 常见灯效（Vial GUI 可选）
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
#define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#define RGBLIGHT_EFFECT_SNAKE
#define RGBLIGHT_EFFECT_KNIGHT
#define RGBLIGHT_EFFECT_CHRISTMAS
#define RGBLIGHT_EFFECT_STATIC_GRADIENT
#define RGBLIGHT_EFFECT_RGB_TEST
#define RGBLIGHT_EFFECT_ALTERNATING
#define RGBLIGHT_EFFECT_TWINKLE
#endif

#define ANALOG_JOYSTICK_X_AXIS_PIN GP26
#define ANALOG_JOYSTICK_Y_AXIS_PIN GP27
#define ANALOG_JOYSTICK_AUTO_AXIS
#define ANALOG_JOYSTICK_CUTOFF
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_COMBINED
#define POINTING_DEVICE_INVERT_X_RIGHT
#define POINTING_DEVICE_INVERT_Y_RIGHT
#define POINTING_DEVICE_INVERT_X

#define POINTING_DEVICE_TASK_THROTTLE_MS 10

#define ANALOG_JOYSTICK_SPEED_MAX 3
#define ANALOG_JOYSTICK_SPEED_REGULATOR 24
