#pragma once

#define VIAL_KEYBOARD_UID {0xD9, 0x57, 0x77, 0x82, 0x51, 0x70, 0x60, 0x25}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define DEBOUNCE 5
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define MASTER_LEFT

#define SERIAL_USART_FULL_DUPLEX  
#define SERIAL_USART_TX_PIN GP0    
#define SERIAL_USART_RX_PIN GP1
