#pragma once

#define VIAL_KEYBOARD_UID {0x05, 0xB7, 0x28, 0xD3, 0xD8, 0x85, 0xB0, 0x28}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define MASTER_LEFT

#define SERIAL_USART_FULL_DUPLEX  
#define SERIAL_USART_TX_PIN GP0    
#define SERIAL_USART_RX_PIN GP1

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define DEBOUNCE 5
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
