#pragma once

#define VIAL_KEYBOARD_UID {0x7D, 0x4F, 0x95, 0x9C, 0x01, 0x2F, 0x3A, 0x95}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define MASTER_LEFT

#define SERIAL_USART_FULL_DUPLEX  
#define SERIAL_USART_TX_PIN GP0    
#define SERIAL_USART_RX_PIN GP1

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define DEBOUNCE 5
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
