#pragma once

#define VIAL_KEYBOARD_UID {0xBB, 0x92, 0x4C, 0x85, 0x68, 0xD2, 0x01, 0xF6}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define MASTER_RIGHT

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define MATRIX_ROW_PINS { GP27, GP26, GP15, GP14 }
#define MATRIX_COL_PINS { GP3, GP4, GP5, GP6, GP7, GP8 }

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define DEBOUNCE 5
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U
